### ISSUE TITLE
Add area information

### ISSUE THREAD

**Issue by chrismytton** [mysociety/argentina-senadores-mendoza#1]
I was wrong when I said these senators didn't have/need area information, sorry!

Looks like the district is available from the same place as the Facebook and Twitter info, so should be something like "1° Distrito".

**Comment by jacksonj04** [comment]
Fixed in https://github.com/mysociety/argentina-senadores-mendoza/commit/385fb20d7ed13fba28850a961b93add7c3534299, also improved start and end dates.
